### PR TITLE
update rockspec to be more dynamic, added latest release

### PR DESCRIPTION
**Pull request by Tieske**

### CODE REVIEW

**Comment by Tieske** [comment]
@alerque not sure this will upload the rockspecs since the tag and 1.4 rockspec is not in the same commit (requirement iirc)

**Comment by alerque** [comment]
Actually with our current logic I think it *will* try to upload when you merge this. The commit being pushed doesn't match a tag, but you'll be pushing a new rockspec to the default branch. Checking for those is an OR condition. Since the tag has never been uploaded to LuaRocks before it should succeed.

**Review by alerque — APPROVED** [review]

**Comment by Tieske** [comment]
here goes ....

**Comment by alerque** [comment]
Seems to have [worked as expected](https://luarocks.org/modules/lunarmodules/lua-lace) to me.

**Comment by Tieske** [comment]
yep worked! I really like that stuff ❤️

**Pull request merged**
